/**
 * The single place a site engine plugs in.
 *
 * nginx, Apache, and OpenLiteSpeed all follow the same sequence on every
 * apply — render a per-site config, stage it **only when its bytes changed**,
 * swap it in, config-test, reload (or restart) the matching `turbopanel-*`
 * unit, and prove over HTTP that the engine still answers. That sequence used
 * to exist three times, once per engine, with the differences buried inside
 * each copy. It lives here once, and the differences are data:
 *
 * - **`configGroup` / `stageSiteConfig`** — nginx and Apache site files are
 *   installed `root:<engineGroup>` `0640` through `sudo -n install`, so the
 *   daemon (which is not root) can neither read nor write them afterwards.
 *   OpenLiteSpeed *fragments* are deliberately daemon-owned instead: the
 *   aggregated `httpd_config.conf` is regenerated by reading every fragment
 *   back, which a privileged-only file would make impossible. Same
 *   unchanged-content discipline either way, different compare strategy.
 * - **`configTest`** — `nginx -t` runs as `tpnginx`, `httpd -t` runs as root,
 *   and `openlitespeed -t` runs as `tpols`.
 * - **`reload`** — always `systemctl reload`, falling back to
 *   `enable --now` on a host that has never started the unit.
 *
 * ## Safe rollout
 *
 * {@link rolloutSiteConfigs} is the transaction every apply goes
 * through. A rendered config is never written straight to its live path:
 *
 * 1. **Stage.** The candidate lands at `<path>.tpnew` — same directory, so the
 *    swap below is a same-filesystem rename, and *not* matching the `*.conf`
 *    glob every engine's main config includes, so the engine cannot see it yet.
 *    The bytes currently live at `<path>` are snapshotted to `<path>.tpprev`
 *    in the same step; that snapshot is the last-known-good config.
 * 2. **Swap.** Every staged candidate for one engine is renamed into place in
 *    one pass. A rename is atomic, so no reader ever sees a half-written vhost.
 * 3. **Config-test.** `nginx -t` / `httpd -t` / `openlitespeed -t` all validate
 *    a *main* config and everything it includes — never a lone fragment — so
 *    the earliest instant an engine-native test can see the candidate is right
 *    after the swap. It runs there, with `<path>.tpprev` still holding the
 *    previous bytes.
 * 4. **Reload**, then **HTTP validation** against each site's loopback listener.
 * 5. **Roll back on any failure.** A failed config-test, a failed reload, or an
 *    engine that stops answering all restore `<path>.tpprev` over `<path>`
 *    (or delete `<path>` when the site is new), then re-test and reload the
 *    restored config. A deploy therefore cannot strand a config on disk that
 *    the engine refuses — the next reload or restart still finds the last
 *    config this host is known to have served.
 *
 * php-fpm is not an engine (it serves no port and owns no vhost) but it shares
 * the stage-test-reload shape, so it is expressed as a driver too — see
 * {@link PHP_FPM_DRIVER} for why it never restarts.
 */

import { join } from "@std/path";
import { logWarn } from "../../logger.ts";
import type { LayoutPaths } from "../../paths/layout.ts";

/** Engines that can serve a site. */
export type SiteEngineId = "caddy" | "nginx" | "apache" | "openlitespeed";

/** Reload order: php-fpm first (see `reloadSiteEngines`), then these. */
export const SITE_ENGINE_ORDER: readonly SiteEngineId[] = Object.freeze(
  ["caddy", "nginx", "apache", "openlitespeed"] as const,
);

/** Injectable command runner for host-free apply/remove tests. */
export type SiteRunResult = {
  success: boolean;
  stdout: string;
  stderr: string;
};

export type SiteRunFn = (
  command: string,
  args: string[],
) => Promise<SiteRunResult>;

/**
 * Suffix of the rendered candidate. Deliberately not `.conf`: every engine's
 * main config includes `sites/*.conf`, so a candidate sitting beside its live
 * path stays invisible to the engine until the swap.
 */
export const CONFIG_CANDIDATE_SUFFIX = ".tpnew";

/** Suffix of the last-known-good snapshot taken before a swap. */
export const CONFIG_PREVIOUS_SUFFIX = ".tpprev";

/** Best-effort unlink of a staging file; a leftover tmp is not a deploy error. */
export async function removeStagedFile(path: string): Promise<void> {
  try {
    await Deno.remove(path);
  } catch {
    // best-effort
  }
}

/**
 * True when `configPath` already holds exactly the staged bytes.
 *
 * Compared through the privileged `run` seam rather than `Deno.readTextFile`:
 * every file this guards is installed `root:<engineGroup>` mode `0640` and the
 * daemon does not run as root, so reading it directly would fail on a real host
 * and report "changed" on every deploy — the exact churn this exists to stop.
 * A `cmp` that cannot answer (destination missing, permission denied, no `cmp`)
 * reports **changed**, so the worst case is the previous always-rewrite path.
 */
export async function ownedConfigFileMatches(
  run: SiteRunFn,
  stagedPath: string,
  configPath: string,
): Promise<boolean> {
  const cmp = await run("sudo", [
    "-n",
    "cmp",
    "-s",
    "--",
    stagedPath,
    configPath,
  ]);
  return cmp.success;
}

/** Daemon-owned compare — `false` when the file is absent or unreadable. */
export async function localFileMatches(
  path: string,
  contents: string,
): Promise<boolean> {
  try {
    return (await Deno.readTextFile(path)) === contents;
  } catch {
    return false;
  }
}

/**
 * One rendered config waiting to be swapped into its live path, plus
 * everything needed to put the previous bytes back.
 *
 * `previousPath` is `null` when the live path did not exist — a brand new site,
 * whose rollback is a delete rather than a restore.
 */
export type StagedConfigWrite = {
  /** How the file is written: privileged (`root:<group>`) or daemon-owned. */
  readonly kind: "owned" | "daemon";
  /** Live path this candidate is destined for. */
  readonly path: string;
  /** Temp path holding the rendered candidate bytes. */
  readonly candidatePath: string;
  /** Temp copy of the last-known-good bytes, or `null` when `path` was new. */
  readonly previousPath: string | null;
  /** True once the candidate has been swapped into `path`. */
  published: boolean;
};

/**
 * Install `contents` at `configPath`; returns whether the file actually
 * **changed**.
 *
 * Byte-identical content is left in place. An ordinary release promote only
 * moves `current`, so every generated vhost and pool is already correct —
 * reinstalling it would force a config-test plus an engine reload for nothing.
 *
 * This is the un-staged form, kept for the site-removal path where there is no
 * candidate to validate: the file being rewritten is the aggregated
 * OpenLiteSpeed main config *after* fragments have already been deleted.
 */
export async function writeOwnedConfigFile(
  run: SiteRunFn,
  configPath: string,
  contents: string,
  group: string,
): Promise<boolean> {
  const tmp = `${configPath}.tmp`;
  await Deno.writeTextFile(tmp, contents, { mode: 0o640 });
  if (await ownedConfigFileMatches(run, tmp, configPath)) {
    await removeStagedFile(tmp);
    return false;
  }
  const install = await run("sudo", [
    "-n",
    "install",
    "-m",
    "0640",
    "-o",
    "root",
    "-g",
    group,
    tmp,
    configPath,
  ]);
  await removeStagedFile(tmp);
  if (!install.success) {
    throw new Error(
      install.stderr || `Failed to install config ${configPath}`,
    );
  }
  return true;
}

/**
 * Stage `contents` for `configPath` without touching the live file.
 *
 * Returns `null` when the bytes are already correct — the unchanged-content
 * rule that keeps a release promote from reloading anything. Otherwise the
 * candidate is installed `root:<group>` `0640` at `<configPath>.tpnew` and the
 * bytes currently live (if any) are snapshotted to `<configPath>.tpprev`.
 */
export async function stageOwnedConfigFile(
  run: SiteRunFn,
  configPath: string,
  contents: string,
  group: string,
): Promise<StagedConfigWrite | null> {
  const tmp = `${configPath}.tmp`;
  await Deno.writeTextFile(tmp, contents, { mode: 0o640 });
  if (await ownedConfigFileMatches(run, tmp, configPath)) {
    await removeStagedFile(tmp);
    return null;
  }
  const candidatePath = `${configPath}${CONFIG_CANDIDATE_SUFFIX}`;
  const install = await run("sudo", [
    "-n",
    "install",
    "-m",
    "0640",
    "-o",
    "root",
    "-g",
    group,
    tmp,
    candidatePath,
  ]);
  await removeStagedFile(tmp);
  if (!install.success) {
    throw new Error(install.stderr || `Failed to stage config ${configPath}`);
  }
  // A copy that fails is the "no live file yet" case: nothing to restore.
  const previousPath = `${configPath}${CONFIG_PREVIOUS_SUFFIX}`;
  const snapshot = await run("sudo", [
    "-n",
    "cp",
    "-p",
    "--",
    configPath,
    previousPath,
  ]);
  return {
    kind: "owned",
    path: configPath,
    candidatePath,
    previousPath: snapshot.success ? previousPath : null,
    published: false,
  };
}

/**
 * Daemon-owned counterpart of {@link stageOwnedConfigFile} — same
 * unchanged-content rule, no privilege escalation, and the file stays readable
 * by the daemon afterwards. Used for OpenLiteSpeed site fragments, which are
 * read back to regenerate the aggregated main config.
 */
export async function stageDaemonConfigFile(
  path: string,
  contents: string,
): Promise<StagedConfigWrite | null> {
  if (await localFileMatches(path, contents)) return null;
  const candidatePath = `${path}${CONFIG_CANDIDATE_SUFFIX}`;
  await Deno.writeTextFile(candidatePath, contents, { mode: 0o640 });
  const previousPath = `${path}${CONFIG_PREVIOUS_SUFFIX}`;
  let snapshotted = false;
  try {
    await Deno.copyFile(path, previousPath);
    snapshotted = true;
  } catch {
    // No live file yet — rollback deletes instead of restoring.
  }
  return {
    kind: "daemon",
    path,
    candidatePath,
    previousPath: snapshotted ? previousPath : null,
    published: false,
  };
}

/** Atomically swap one staged candidate into its live path. */
export async function publishStagedConfig(
  run: SiteRunFn,
  staged: StagedConfigWrite,
): Promise<void> {
  if (staged.kind === "daemon") {
    await Deno.rename(staged.candidatePath, staged.path);
  } else {
    const mv = await run("sudo", [
      "-n",
      "mv",
      "-f",
      "--",
      staged.candidatePath,
      staged.path,
    ]);
    if (!mv.success) {
      throw new Error(mv.stderr || `Failed to install config ${staged.path}`);
    }
  }
  staged.published = true;
}

/** Drop the candidate/snapshot temp files; leftovers are not a deploy error. */
async function discardStagedArtifacts(
  run: SiteRunFn,
  staged: StagedConfigWrite,
): Promise<void> {
  const leftovers = [staged.candidatePath];
  if (staged.previousPath) leftovers.push(staged.previousPath);
  for (const path of leftovers) {
    if (staged.kind === "daemon") {
      await removeStagedFile(path);
      continue;
    }
    await run("sudo", ["-n", "rm", "-f", "--", path]);
  }
}

/** Keep a published swap: only the temp candidate/snapshot are cleaned up. */
export async function commitStagedConfig(
  run: SiteRunFn,
  staged: StagedConfigWrite,
): Promise<void> {
  await discardStagedArtifacts(run, staged);
}

/**
 * Put the last-known-good bytes back at `staged.path` — or delete the path when
 * the site was new — and clean up the temp files either way.
 */
export async function restoreStagedConfig(
  run: SiteRunFn,
  staged: StagedConfigWrite,
): Promise<void> {
  if (staged.published) {
    if (staged.previousPath) {
      if (staged.kind === "daemon") {
        await Deno.rename(staged.previousPath, staged.path);
      } else {
        await run("sudo", [
          "-n",
          "mv",
          "-f",
          "--",
          staged.previousPath,
          staged.path,
        ]);
      }
    } else if (staged.kind === "daemon") {
      await removeStagedFile(staged.path);
    } else {
      await run("sudo", ["-n", "rm", "-f", "--", staged.path]);
    }
    staged.published = false;
  }
  await discardStagedArtifacts(run, staged);
}

/**
 * `systemctl reload` (or `restart`) with the same "not installed / not started
 * yet" fallback every engine here uses.
 *
 * `restart` is asked for only when the engine's **group membership** changed
 * this apply: supplementary groups are resolved when a process starts, so a
 * reload would leave already-running workers unable to read a release tree they
 * only just gained group access to.
 */
export async function systemctlReloadOrStart(
  run: SiteRunFn,
  unit: string,
  restart: boolean,
  label = unit,
): Promise<void> {
  const action = restart ? "restart" : "reload";
  const reload = await run("sudo", ["-n", "systemctl", action, unit]);
  if (reload.success) return;
  // First deploy may need start instead of reload.
  const start = await run("sudo", [
    "-n",
    "systemctl",
    "enable",
    "--now",
    unit,
  ]);
  if (!start.success) {
    throw new Error(
      reload.stderr || start.stderr || `Failed to reload/start ${label}`,
    );
  }
}

/** One loopback endpoint a reloaded engine has to answer on. */
export type SiteValidationTarget = Readonly<{
  /** Compose service the URL belongs to — used in the failure message. */
  label: string;
  /** Loopback URL to probe, e.g. `http://127.0.0.1:18080/`. */
  url: string;
}>;

/** Attempts per endpoint before a reload is declared a failure. */
const VALIDATION_ATTEMPTS = 3;

/**
 * Prove the reloaded engine still serves every site it owns.
 *
 * Any HTTP status below 500 counts: a site may legitimately answer 403 or 404
 * (no index file yet, an app-level route), and what this step exists to catch
 * is the engine that came back refusing connections or failing every request
 * because the config it was just handed is wrong in a way `-t` cannot see.
 *
 * The probe runs through the injected `run` seam (`curl`, already a host
 * prerequisite for the vendoring playbooks) so an apply stays testable without
 * a live listener.
 */
export async function validateSiteEndpoints(
  run: SiteRunFn,
  label: string,
  targets: readonly SiteValidationTarget[],
): Promise<void> {
  for (const target of targets) {
    let failure = "no response";
    let answered = false;
    for (let attempt = 0; attempt < VALIDATION_ATTEMPTS; attempt += 1) {
      const probe = await run("curl", [
        "-sS",
        "-o",
        "/dev/null",
        "-w",
        "%{http_code}",
        "--max-time",
        "5",
        target.url,
      ]);
      if (!probe.success) {
        failure = probe.stderr || "request failed";
        continue;
      }
      const status = Number.parseInt(probe.stdout.trim(), 10);
      if (Number.isFinite(status) && status > 0 && status < 500) {
        answered = true;
        break;
      }
      failure = `HTTP ${probe.stdout.trim() || "?"}`;
    }
    if (!answered) {
      throw new Error(
        `${label} did not serve ${target.label} at ${target.url} after reload: ${failure}`,
      );
    }
  }
}

/** One engine's render → stage → swap → test → reload behavior. */
export type SiteEngineDriver = {
  readonly engine: SiteEngineId;
  /** Human label for logs and error messages. */
  readonly label: string;
  /** systemd unit this engine is reloaded through. */
  readonly unit: string;
  /**
   * Unix group generated site config is installed to, or `null` when this
   * engine's site files stay daemon-owned (OpenLiteSpeed fragments).
   */
  readonly configGroup: string | null;
  /**
   * Stage one rendered site config beside its live path; `null` when the bytes
   * are already correct.
   */
  stageSiteConfig(
    run: SiteRunFn,
    path: string,
    contents: string,
  ): Promise<StagedConfigWrite | null>;
  /** Validate what is on disk before handing it to systemd. */
  configTest(run: SiteRunFn, layout: LayoutPaths): Promise<void>;
  /** config-test, then reload (or restart) the unit. */
  reload(
    run: SiteRunFn,
    layout: LayoutPaths,
    restart: boolean,
  ): Promise<void>;
};

function nginxBinaryPath(layout: LayoutPaths): string {
  return join(layout.runtimesDir, "nginx", "current", "sbin", "nginx");
}

function nginxMainConfigPath(layout: LayoutPaths): string {
  return join(layout.configDir, "nginx", "nginx.conf");
}

function apacheBinaryPath(layout: LayoutPaths): string {
  return join(layout.runtimesDir, "apache", "current", "bin", "httpd");
}

function apacheMainConfigPath(layout: LayoutPaths): string {
  return join(layout.configDir, "apache", "httpd.conf");
}

/**
 * Vendored OpenLiteSpeed server binary — the same one `lswsctrl` execs, and
 * the only thing on the host that can parse `httpd_config.conf`.
 */
export function openlitespeedBinaryPath(layout: LayoutPaths): string {
  return join(
    layout.runtimesDir,
    "openlitespeed",
    "current",
    "bin",
    "openlitespeed",
  );
}

function openlitespeedMainConfigPath(layout: LayoutPaths): string {
  return join(layout.configDir, "openlitespeed", "httpd_config.conf");
}

/**
 * php-fpm series pin. Must match `php_fpm_series` in
 * `orchestration/roles/php-fpm/defaults/main.yml`, and is re-exported as
 * `DEFAULT_PHP_SERIES` from `../site.ts` so there is one literal. It is a
 * default, not a pin: several series co-install and `resolveSitePhpSeries`
 * picks per site.
 */
export const DEFAULT_PHP_FPM_SERIES = "8.4";

/**
 * php-fpm is installed from the sury Debian repo, not vendored — so the binary
 * lives at an apt path, one per co-installed series, and never under
 * `runtimesDir`. Taking the series as a parameter (rather than reading the pin
 * here) is what lets a caller test one series' master without touching another.
 */
function phpFpmBinaryPath(series: string): string {
  return `/usr/sbin/php-fpm${series}`;
}

function phpFpmMainConfigPath(layout: LayoutPaths, series: string): string {
  return join(layout.configDir, "php", series, "php-fpm.conf");
}

/**
 * The **site** Caddy — a second, unprivileged Caddy process, distinct from the
 * edge Caddy that owns public `:80`/`:443`.
 *
 * Same binary, two processes. The edge one runs as root, owns the internal CA
 * and every tenant leaf key, and writes its site files with a bare write plus a
 * best-effort reload whose failure is only logged — acceptable for
 * `reverse_proxy` one-liners, not for tenant document roots and PHP handlers.
 * Serving sites from a separate unprivileged unit puts them through the same
 * staged `.tpnew`/`.tpprev` transaction every other engine gets, and keeps the
 * loopback `listenPort` that `site-docker.ts` hands containers as
 * `host.docker.internal:<port>`.
 */
function siteCaddyBinaryPath(layout: LayoutPaths): string {
  return join(layout.runtimesDir, "caddy", "current", "caddy");
}

function siteCaddyMainConfigPath(layout: LayoutPaths): string {
  return join(layout.configDir, "caddy", "Caddyfile");
}

/**
 * Caddy writes its own data (certificate cache, even with `auto_https off`)
 * under `$XDG_DATA_HOME`. Pin it so a `sudo -u` validate never falls back to a
 * home directory `tpcaddysite` does not own.
 */
function siteCaddyDataDir(layout: LayoutPaths): string {
  return join(layout.stateDir, "site-caddy");
}

export const NGINX_DRIVER: SiteEngineDriver = {
  engine: "nginx",
  label: "nginx",
  unit: "turbopanel-nginx",
  configGroup: "tpnginx",
  stageSiteConfig(run, path, contents) {
    return stageOwnedConfigFile(run, path, contents, "tpnginx");
  },
  async configTest(run, layout) {
    // Run -t as tpnginx: the nginx.org binary defaults to user "nginx", and a
    // root-owned configtest looks that user up even without a `user` directive.
    // The systemd unit also runs as tpnginx (high-port vhosts only).
    const test = await run("sudo", [
      "-n",
      "-u",
      "tpnginx",
      "--",
      nginxBinaryPath(layout),
      "-t",
      "-c",
      nginxMainConfigPath(layout),
    ]);
    if (!test.success) {
      throw new Error(test.stderr || "nginx -t failed");
    }
  },
  async reload(run, layout, restart) {
    await this.configTest(run, layout);
    await systemctlReloadOrStart(run, this.unit, restart, this.label);
  },
};

export const APACHE_DRIVER: SiteEngineDriver = {
  engine: "apache",
  label: "apache",
  unit: "turbopanel-apache",
  configGroup: "tpapache",
  stageSiteConfig(run, path, contents) {
    return stageOwnedConfigFile(run, path, contents, "tpapache");
  },
  async configTest(run, layout) {
    const test = await run("sudo", [
      "-n",
      apacheBinaryPath(layout),
      "-t",
      "-f",
      apacheMainConfigPath(layout),
    ]);
    if (!test.success) {
      throw new Error(test.stderr || "httpd -t failed");
    }
  },
  async reload(run, layout, restart) {
    await this.configTest(run, layout);
    await systemctlReloadOrStart(run, this.unit, restart, this.label);
  },
};

export const OPENLITESPEED_DRIVER: SiteEngineDriver = {
  engine: "openlitespeed",
  label: "OpenLiteSpeed",
  unit: "turbopanel-openlitespeed",
  // Fragments stay daemon-owned so the aggregated httpd_config.conf can be
  // regenerated by reading every currently-active fragment back.
  configGroup: null,
  stageSiteConfig(_run, path, contents) {
    return stageDaemonConfigFile(path, contents);
  },
  async configTest(run, layout) {
    // `openlitespeed -t` parses httpd_config.conf plus every per-vhost
    // configFile it names and exits without binding a port. Run it as tpols,
    // the account the unit runs as: the parse resolves each vhost's suEXEC
    // user/group and its LSAPI socket path relative to the server root, so a
    // root-owned test would validate paths the service can never reach.
    const test = await run("sudo", [
      "-n",
      "-u",
      "tpols",
      "--",
      openlitespeedBinaryPath(layout),
      "-t",
      "-c",
      openlitespeedMainConfigPath(layout),
    ]);
    if (!test.success) {
      throw new Error(test.stderr || "openlitespeed -t failed");
    }
  },
  async reload(run, layout, restart) {
    // `systemctl reload` maps to `lswsctrl restart` (graceful, zero-downtime —
    // OpenLiteSpeed has no separate "reload" signal distinct from restart), and
    // a restart is exactly where an unvalidated config would surface as
    // downtime, so the config-test above always runs first.
    await this.configTest(run, layout);
    await systemctlReloadOrStart(run, this.unit, restart, this.label);
  },
};

export const CADDY_DRIVER: SiteEngineDriver = {
  engine: "caddy",
  label: "Caddy",
  unit: "turbopanel-site-caddy",
  configGroup: "tpcaddysite",
  stageSiteConfig(run, path, contents) {
    return stageOwnedConfigFile(run, path, contents, "tpcaddysite");
  },
  async configTest(run, layout) {
    // `caddy validate` parses the main Caddyfile *and* everything it imports,
    // and exits without binding a port — the property this interface requires
    // of every engine's test. Run it as the unit's own account so any path it
    // resolves is one the service can actually reach.
    const test = await run("sudo", [
      "-n",
      "-u",
      "tpcaddysite",
      "--",
      "env",
      `XDG_DATA_HOME=${siteCaddyDataDir(layout)}`,
      siteCaddyBinaryPath(layout),
      "validate",
      "--adapter",
      "caddyfile",
      "--config",
      siteCaddyMainConfigPath(layout),
    ]);
    if (!test.success) {
      throw new Error(test.stderr || "caddy validate failed");
    }
  },
  async reload(run, layout, restart) {
    await this.configTest(run, layout);
    await systemctlReloadOrStart(run, this.unit, restart, this.label);
  },
};

export const SITE_ENGINE_DRIVERS: Readonly<
  Record<SiteEngineId, SiteEngineDriver>
> = Object.freeze({
  caddy: CADDY_DRIVER,
  nginx: NGINX_DRIVER,
  apache: APACHE_DRIVER,
  openlitespeed: OPENLITESPEED_DRIVER,
});

/**
 * php-fpm's own test-then-reload step. Not a {@link SiteEngineDriver}
 * — it serves no port and owns no site config — but the same shape, and it is
 * always reloaded *before* the engines so their config-tests find live sockets.
 *
 * It is never restarted for group membership: FPM workers run as the
 * *principal*, which owns the release group already; only the engine service
 * accounts have to join it.
 */
/**
 * One php-fpm master, for one series.
 *
 * A factory rather than a constant because a master is one binary: co-installed
 * series run as separate `turbopanel-php-fpm@<series>` instances, each with its
 * own config, pool glob, pidfile, and socket directory. Rolling out a site on
 * 8.3 must not touch the 8.4 master serving everything else.
 */
export type PhpFpmDriver = SiteRolloutUnit & {
  reload(run: SiteRunFn, layout: LayoutPaths): Promise<void>;
};

export function phpFpmDriver(series: string): PhpFpmDriver {
  const unit = `turbopanel-php-fpm@${series}`;
  const driver: PhpFpmDriver = {
    label: `php-fpm ${series}`,
    unit,
    async configTest(run: SiteRunFn, layout: LayoutPaths): Promise<void> {
      const test = await run("sudo", [
        "-n",
        phpFpmBinaryPath(series),
        "--fpm-config",
        phpFpmMainConfigPath(layout, series),
        "--test",
      ]);
      if (!test.success) {
        throw new Error(test.stderr || `php-fpm ${series} --test failed`);
      }
    },
    async reload(run: SiteRunFn, layout: LayoutPaths): Promise<void> {
      await driver.configTest(run, layout);
      // Never restarted for group membership: FPM workers run as the
      // *principal*, which owns the release group already — only the engine
      // service accounts have to join it.
      await systemctlReloadOrStart(run, unit, false, driver.label);
    },
  };
  return driver;
}

/** The subset of a driver {@link rolloutSiteConfigs} needs. */
export type SiteRolloutUnit = {
  readonly label: string;
  readonly unit: string;
  configTest(run: SiteRunFn, layout: LayoutPaths): Promise<void>;
};

export type SiteRolloutOpts = {
  run: SiteRunFn;
  layout: LayoutPaths;
  /** Engine (or php-fpm) being rolled out. */
  target: SiteRolloutUnit;
  /** Restart instead of reload — new supplementary group membership. */
  restart: boolean;
  /** Candidates to swap in, in dependency order. */
  staged: readonly StagedConfigWrite[];
  /** Loopback endpoints that must answer once the unit is back. */
  validationTargets?: readonly SiteValidationTarget[];
  /**
   * Runs once every staged candidate above is live, before the config-test.
   * OpenLiteSpeed uses it to regenerate `httpd_config.conf` from the fragments
   * that were just published; any config it stages joins the same transaction.
   */
  afterPublish?: () => Promise<StagedConfigWrite | null>;
};

/**
 * Put the last-known-good config back and get the unit serving it again.
 *
 * Best-effort by design: the caller is already throwing the failure that got us
 * here, and a rollback that cannot re-test or re-reload must not replace that
 * error with its own.
 */
async function rollbackSiteConfigs(
  opts: SiteRolloutOpts,
  published: readonly StagedConfigWrite[],
): Promise<void> {
  for (const staged of published) {
    try {
      await restoreStagedConfig(opts.run, staged);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      logWarn(
        "deploy",
        `${opts.target.label} could not restore ${staged.path}: ${message}`,
      );
    }
  }
  if (published.length === 0) return;
  try {
    await opts.target.configTest(opts.run, opts.layout);
    await systemctlReloadOrStart(
      opts.run,
      opts.target.unit,
      false,
      opts.target.label,
    );
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    logWarn(
      "deploy",
      `${opts.target.label} rollback reload failed: ${message}`,
    );
  }
}

/**
 * Swap → config-test → reload → HTTP-validate, rolling the whole set back to
 * the last-known-good config if any of those steps fails.
 *
 * See the module header for why the config-test cannot run before the swap:
 * every engine here tests a main config and its includes, never a lone
 * fragment. The snapshot taken at staging time is what makes the swap safe.
 */
export async function rolloutSiteConfigs(
  opts: SiteRolloutOpts,
): Promise<void> {
  const published: StagedConfigWrite[] = [];
  try {
    for (const staged of opts.staged) {
      await publishStagedConfig(opts.run, staged);
      published.push(staged);
    }
    const aggregated = await opts.afterPublish?.();
    if (aggregated) {
      await publishStagedConfig(opts.run, aggregated);
      published.push(aggregated);
    }
    await opts.target.configTest(opts.run, opts.layout);
    await systemctlReloadOrStart(
      opts.run,
      opts.target.unit,
      opts.restart,
      opts.target.label,
    );
    await validateSiteEndpoints(
      opts.run,
      opts.target.label,
      opts.validationTargets ?? [],
    );
  } catch (err) {
    await rollbackSiteConfigs(opts, published);
    throw err;
  }
  for (const staged of published) {
    await commitStagedConfig(opts.run, staged);
  }
}
