sonar.projectKey=turbopanel_turbopaneld
sonar.projectName=turbopaneld

sonar.exclusions=\
  dist/**,\
  publish/**,\
  state/**,\
  logs/**,\
  cloudflared/**,\
  node_modules/**,\
  coverage/**,\
  src/build-info.ts,\
  **/orchestration/roles/geerlingguy.docker/**

sonar.coverage.exclusions=\
  dist/**,\
  publish/**,\
  src/build-info.ts,\
  **/*.test.ts,\
  **/orchestration/roles/geerlingguy.docker/**
