---
galaxy_info:
  author: turbopanel
  description: >-
    Compile the self-hosted instance into a single binary when
    turbopanel_instance_run_mode is compiled.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Raspbian
      versions:
        - all

dependencies: []
