---
- name: Check Tilt binary
  ansible.builtin.stat:
    path: /usr/local/bin/tilt
  register: _tilt_bin

- name: Install Tilt
  when: not _tilt_bin.stat.exists
  ansible.builtin.shell: |
    set -euo pipefail
    curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
  args:
    creates: /usr/local/bin/tilt
