---
- name: Install agent prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - git
      - gnupg
      - iptables
      - pamtester
      - python3-debian
      - tar
      - unzip
      - xz-utils
    state: present
    update_cache: true
