---
turbopanel_install_root: /opt/turbopanel
turbopanel_user: turbopanel
turbopanel_runtimes_dir: "{{ turbopanel_install_root }}/runtimes"
turbopanel_platform_dir: "{{ turbopanel_install_root }}/platform"
turbopanel_instance_dir: "{{ turbopanel_platform_dir }}/instance"
instance_user: instance
turbopanel_group: turbopanel
turbopanel_instance_run_mode: source
turbopanel_instance_dist_dir: "{{ turbopanel_instance_dir }}/dist"
turbopanel_instance_binary: "{{ turbopanel_instance_dist_dir }}/turbopanel-instance"
force_compile: false
