---
- name: Reload systemd for instance units
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart turbopanel instance
  ansible.builtin.systemd:
    name: "{{ instance_service_name }}"
    state: restarted
  when: instance_start | bool

- name: Restart turbopanel caddy
  ansible.builtin.systemd:
    name: "{{ caddy_service_name }}"
    state: restarted
  when: instance_start | bool

- name: Restart turbopanel ui
  ansible.builtin.systemd:
    name: "{{ ui_service_name }}"
    state: restarted
  when:
    - instance_start | bool
    - turbopanel_ui_mode == 'dev'

- name: Restart turbopanel website
  ansible.builtin.systemd:
    name: "{{ website_service_name }}"
    state: restarted
  when:
    - instance_start | bool
    - turbopanel_dev_user | default('') | length > 0
    - (turbopanel_instance_runtime | default('deno')) == 'workers'

- name: Restart turbopanel mailer
  ansible.builtin.systemd:
    name: "{{ mailer_service_name }}"
    state: restarted
  when: instance_start | bool

- name: Restart turbopanel dbstudio
  ansible.builtin.systemd:
    name: "{{ dbstudio_service_name }}"
    state: restarted
  when:
    - instance_start | bool
    - turbopanel_ui_mode == 'dev'
