/**
 * Pure renderers for the scheduled-backup unit family:
 * `turbopanel-backup-<policyId>.timer` fires `turbopanel-backup-<policyId>.service`,
 * a oneshot that runs `<lib>/tp-backup-run <policyId>` as the daemon account.
 *
 * The shape is pinned by tp-host's unit check (orchestration/scripts/tp-host,
 * `tp_backup_unit_ok`): the service must run as exactly the daemon account,
 * with exactly this one ExecStart for the policy id in its own name, the
 * daemon env file and nothing else that could steer it. Change a line here and
 * that check (and `src/permissions/tp-host.test.ts`) in the same commit.
 *
 * Nothing here touches the host — `./reconcile.ts` owns every write.
 */

import type { LayoutPaths } from "../paths/layout.ts";
import { SYSTEMD_UNIT_DIR } from "../deploy/native/unit.ts";

/** Unit-name prefix; everything under it belongs to this family and is swept. */
export const BACKUP_UNIT_PREFIX = "turbopanel-backup-";

/**
 * The account a backup runs as: the daemon's own (the one that already reads
 * the policies file and reaches Docker). tp-host accepts exactly this name.
 */
export const BACKUP_UNIT_ACCOUNT = "tp";

/** A dump that has not finished in this long is stopped and recorded failed. */
export const BACKUP_TIMEOUT_START_SEC = "6h";

/**
 * Spread policies that share a schedule across hosts and engines, but only
 * where the gap between runs is long enough for a spread to be small next to
 * it. A daily or weekly policy may start up to this late.
 */
export const BACKUP_RANDOMIZED_DELAY_SEC = 300;

/** An hourly (or every-few-hours) policy may start up to this late. */
export const BACKUP_HOURLY_RANDOMIZED_DELAY_SEC = 30;

/**
 * A policy that fires more than once an hour must fire when it says it will:
 * no random delay, and systemd's one-minute timer coalescing tightened too.
 */
export const BACKUP_SUBHOURLY_ACCURACY_SEC = "1s";

const SINGLE_NUMBER_RE = /^\d{1,2}$/;
const CLOCK_RE = /^([^:\s]+):([^:\s]+):([^:\s]+)$/;

/**
 * How late a timer may start, read from the `OnCalendar` value it is sent
 * (`[Dow ]*-M-D H:M:00[ Zone]`, as the control plane renders it):
 * - minute field not a single number (`*`, a step or a list): runs more than
 *   once an hour, so no delay and a tight accuracy;
 * - minute fixed but hour field not a single number: hourly or every few
 *   hours, a short spread;
 * - both fixed (daily, weekly, monthly): the full spread.
 * A value this cannot read gets no delay: an unreadable schedule is never
 * made later than it asked.
 */
export function backupTimerTiming(onCalendar: string): {
  randomizedDelaySec: number;
  accuracySec: string | null;
} {
  const clock = onCalendar
    .split(" ")
    .map((token) => CLOCK_RE.exec(token))
    .find((match) => match !== null);
  if (!clock) {
    return {
      randomizedDelaySec: 0,
      accuracySec: BACKUP_SUBHOURLY_ACCURACY_SEC,
    };
  }
  const [, hour, minute] = clock;
  if (!SINGLE_NUMBER_RE.test(minute)) {
    return {
      randomizedDelaySec: 0,
      accuracySec: BACKUP_SUBHOURLY_ACCURACY_SEC,
    };
  }
  if (!SINGLE_NUMBER_RE.test(hour)) {
    return {
      randomizedDelaySec: BACKUP_HOURLY_RANDOMIZED_DELAY_SEC,
      accuracySec: null,
    };
  }
  return { randomizedDelaySec: BACKUP_RANDOMIZED_DELAY_SEC, accuracySec: null };
}

const POLICY_ID_RE =
  /^[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/;

/** `turbopanel-backup-<policyId>` (no extension); refuses anything but a lower-case UUID. */
export function backupUnitName(policyId: string): string {
  if (!POLICY_ID_RE.test(policyId)) {
    throw new Error("backup policy id must be a lower-case UUID");
  }
  return `${BACKUP_UNIT_PREFIX}${policyId}`;
}

export function backupServicePath(
  policyId: string,
  unitDir: string = SYSTEMD_UNIT_DIR,
): string {
  return `${unitDir}/${backupUnitName(policyId)}.service`;
}

export function backupTimerPath(
  policyId: string,
  unitDir: string = SYSTEMD_UNIT_DIR,
): string {
  return `${unitDir}/${backupUnitName(policyId)}.timer`;
}

/**
 * The oneshot that runs one scheduled backup. No `[Install]`: only its timer
 * starts it, so nothing runs a backup at boot as a side effect.
 */
export function backupServiceContent(
  layout: Pick<LayoutPaths, "libDir" | "configDir">,
  policyId: string,
): string {
  const unit = backupUnitName(policyId);
  return [
    "# Managed by TurboPanel — regenerated by server.backups.reconcile; edits are overwritten.",
    "[Unit]",
    `Description=TurboPanel scheduled backup ${policyId}`,
    "After=docker.service",
    "",
    "[Service]",
    "Type=oneshot",
    `User=${BACKUP_UNIT_ACCOUNT}`,
    `Group=${BACKUP_UNIT_ACCOUNT}`,
    `EnvironmentFile=-${layout.configDir}/daemon.env`,
    `ExecStart=${layout.libDir}/tp-backup-run ${policyId}`,
    "NoNewPrivileges=yes",
    "CapabilityBoundingSet=",
    "AmbientCapabilities=",
    `TimeoutStartSec=${BACKUP_TIMEOUT_START_SEC}`,
    // A dump reads the whole engine; it should yield to the apps it protects.
    "Nice=10",
    "IOSchedulingClass=idle",
    "StandardOutput=journal",
    "StandardError=journal",
    `SyslogIdentifier=${unit}`,
    "",
  ].join("\n");
}

/**
 * The timer. `Persistent=true` on purpose, unlike tenant cron: a backup a host
 * missed while it was off runs once when it comes back (the owner's choice,
 * 2026-09-30), rather than leaving a gap until the next scheduled time.
 * `onCalendar` arrives validated by the reconcile contract parser.
 */
export function backupTimerContent(
  policyId: string,
  onCalendar: string,
): string {
  const unit = backupUnitName(policyId);
  const timing = backupTimerTiming(onCalendar);
  return [
    "# Managed by TurboPanel — regenerated by server.backups.reconcile; edits are overwritten.",
    "[Unit]",
    `Description=TurboPanel backup schedule ${policyId}`,
    "",
    "[Timer]",
    `Unit=${unit}.service`,
    `OnCalendar=${onCalendar}`,
    ...(timing.accuracySec ? [`AccuracySec=${timing.accuracySec}`] : []),
    `RandomizedDelaySec=${timing.randomizedDelaySec}`,
    "Persistent=true",
    "",
    "[Install]",
    "WantedBy=timers.target",
    "",
  ].join("\n");
}
