/**
 * Pure renderers for the scheduled-backup unit family:
 * `turbopanel-backup-<policyId>.timer` fires `turbopanel-backup-<policyId>.service`,
 * a oneshot that runs `<lib>/tp-backup-run <policyId>` as the daemon account.
 *
 * The shape is pinned by tp-host's unit check (orchestration/scripts/tp-host,
 * `tp_backup_unit_ok`): the service must run as exactly the daemon account,
 * with exactly this one ExecStart for the policy id in its own name, the
 * daemon env file and nothing else that could steer it. Change a line here and
 * that check (and `src/permissions/tp-host.test.ts`) in the same commit.
 *
 * Nothing here touches the host — `./reconcile.ts` owns every write.
 */

import type { LayoutPaths } from "../paths/layout.ts";
import { SYSTEMD_UNIT_DIR } from "../deploy/native/unit.ts";

/** Unit-name prefix; everything under it belongs to this family and is swept. */
export const BACKUP_UNIT_PREFIX = "turbopanel-backup-";

/**
 * The account a backup runs as: the daemon's own (the one that already reads
 * the policies file and reaches Docker). tp-host accepts exactly this name.
 */
export const BACKUP_UNIT_ACCOUNT = "tp";

/** A dump that has not finished in this long is stopped and recorded failed. */
export const BACKUP_TIMEOUT_START_SEC = "6h";

/** Spread policies that share a schedule across hosts and engines. */
export const BACKUP_RANDOMIZED_DELAY_SEC = 300;

const POLICY_ID_RE =
  /^[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/;

/** `turbopanel-backup-<policyId>` (no extension); refuses anything but a lower-case UUID. */
export function backupUnitName(policyId: string): string {
  if (!POLICY_ID_RE.test(policyId)) {
    throw new Error("backup policy id must be a lower-case UUID");
  }
  return `${BACKUP_UNIT_PREFIX}${policyId}`;
}

export function backupServicePath(
  policyId: string,
  unitDir: string = SYSTEMD_UNIT_DIR,
): string {
  return `${unitDir}/${backupUnitName(policyId)}.service`;
}

export function backupTimerPath(
  policyId: string,
  unitDir: string = SYSTEMD_UNIT_DIR,
): string {
  return `${unitDir}/${backupUnitName(policyId)}.timer`;
}

/**
 * The oneshot that runs one scheduled backup. No `[Install]`: only its timer
 * starts it, so nothing runs a backup at boot as a side effect.
 */
export function backupServiceContent(
  layout: Pick<LayoutPaths, "libDir" | "configDir">,
  policyId: string,
): string {
  const unit = backupUnitName(policyId);
  return [
    "# Managed by TurboPanel — regenerated by server.backups.reconcile; edits are overwritten.",
    "[Unit]",
    `Description=TurboPanel scheduled backup ${policyId}`,
    "After=docker.service",
    "",
    "[Service]",
    "Type=oneshot",
    `User=${BACKUP_UNIT_ACCOUNT}`,
    `Group=${BACKUP_UNIT_ACCOUNT}`,
    `EnvironmentFile=-${layout.configDir}/daemon.env`,
    `ExecStart=${layout.libDir}/tp-backup-run ${policyId}`,
    "NoNewPrivileges=yes",
    "CapabilityBoundingSet=",
    "AmbientCapabilities=",
    `TimeoutStartSec=${BACKUP_TIMEOUT_START_SEC}`,
    // A dump reads the whole engine; it should yield to the apps it protects.
    "Nice=10",
    "IOSchedulingClass=idle",
    "StandardOutput=journal",
    "StandardError=journal",
    `SyslogIdentifier=${unit}`,
    "",
  ].join("\n");
}

/**
 * The timer. `Persistent=true` on purpose, unlike tenant cron: a backup a host
 * missed while it was off runs once when it comes back (the owner's choice,
 * 2026-09-30), rather than leaving a gap until the next scheduled time.
 * `onCalendar` arrives validated by the reconcile contract parser.
 */
export function backupTimerContent(
  policyId: string,
  onCalendar: string,
): string {
  const unit = backupUnitName(policyId);
  return [
    "# Managed by TurboPanel — regenerated by server.backups.reconcile; edits are overwritten.",
    "[Unit]",
    `Description=TurboPanel backup schedule ${policyId}`,
    "",
    "[Timer]",
    `Unit=${unit}.service`,
    `OnCalendar=${onCalendar}`,
    `RandomizedDelaySec=${BACKUP_RANDOMIZED_DELAY_SEC}`,
    "Persistent=true",
    "",
    "[Install]",
    "WantedBy=timers.target",
    "",
  ].join("\n");
}
