# TurboPanel vendored runtime root (POSIX sh).
# Source after paths are needed; override with TURBOPANEL_RUNTIMES_DIR.

TURBOPANEL_HOME="${TURBOPANEL_HOME:-/opt/turbopanel}"
TURBOPANEL_RUNTIMES_DIR="${TURBOPANEL_RUNTIMES_DIR:-${TURBOPANEL_HOME}/vendor}"
RUNTIMES_DIR="${RUNTIMES_DIR:-$TURBOPANEL_RUNTIMES_DIR}"
export TURBOPANEL_HOME TURBOPANEL_RUNTIMES_DIR RUNTIMES_DIR
