---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart turbopanel daemon
  ansible.builtin.systemd:
    name: "{{ turbopanel_service_name }}"
    state: restarted
  when: turbopanel_start | bool
