/**
 * Names that must never be a site owner's Linux user: they belong to the
 * host's own accounts and groups. The root helper keeps its own copy; a
 * request that reaches the daemon is checked here first so useradd/groupadd
 * never run for one of these names.
 */

const TP_HOST_RESERVED_NAMES = [
  "root",
  "daemon",
  "bin",
  "sys",
  "sync",
  "games",
  "man",
  "lp",
  "mail",
  "news",
  "uucp",
  "proxy",
  "www-data",
  "backup",
  "list",
  "irc",
  "gnats",
  "nobody",
  "nogroup",
  "sshd",
  "ssh",
  "_ssh",
  "_apt",
  "_chrony",
  "postgres",
  "redis",
  "mysql",
  "docker",
  "containers",
  "adm",
  "admin",
  "audio",
  "avahi",
  "cdrom",
  "crontab",
  "dialout",
  "dip",
  "disk",
  "floppy",
  "fuse",
  "incus",
  "incus-admin",
  "input",
  "kmem",
  "kvm",
  "libvirt",
  "libvirt-qemu",
  "lpadmin",
  "lxd",
  "messagebus",
  "microk8s",
  "netdev",
  "operator",
  "plugdev",
  "polkitd",
  "render",
  "sambashare",
  "sasl",
  "sgx",
  "shadow",
  "src",
  "ssl-cert",
  "staff",
  "sudo",
  "tape",
  "tty",
  "users",
  "utmp",
  "video",
  "voice",
  "wheel",
  "bluetooth",
  "gpio",
  "i2c",
  "nopasswdlogin",
  "rdma",
  "scanner",
  "syslog",
  "systemd-journal",
  "tss",
  "uuidd",
  "vboxusers",
  "wireshark",
] as const;

const PLATFORM_ACCOUNT_NAMES = [
  "tp",
  "tpctrl",
  "tpcache",
  "tpdata",
  "tpqueue",
  "tpmetrics",
  "tpcaddy",
  "tpnginx",
  "tpapache",
  "tpols",
  "tplsws",
  "containers",
  "tpbuild",
  "systemd-journal",
] as const;

const ADDITIONAL_HOST_ACCOUNT_NAMES = [
  "ftp",
  "sftp",
  "git",
  "www",
  "httpd",
  "apache",
  "nginx",
  "ubuntu",
  "debian",
  "pi",
  "vagrant",
  "ec2-user",
  "ssm-user",
  "opc",
  "postfix",
  "dovecot",
  "vmail",
  "clamav",
  "opendkim",
  "mongodb",
  "mariadb",
  "memcache",
  "elasticsearch",
  "openldap",
  "unbound",
  "chrony",
  "ntp",
  "lightdm",
  "gdm",
  "pulse",
  "rtkit",
  "colord",
  "geoclue",
  "saned",
  "dnsmasq",
  "landscape",
  "lxc",
] as const;

/** Exact names that cannot be a site owner's Linux user. */
export const RESERVED_PRINCIPAL_USERNAMES: ReadonlySet<string> = new Set([
  ...TP_HOST_RESERVED_NAMES,
  ...PLATFORM_ACCOUNT_NAMES,
  ...ADDITIONAL_HOST_ACCOUNT_NAMES,
]);

/**
 * True when `value` (trimmed, compared in lower case) is reserved for the
 * host's own accounts, starts with `tp` or `systemd-`, or ends with `-grp`.
 */
export function isReservedPrincipalUsername(value: string): boolean {
  const name = value.trim().toLowerCase();
  if (name.length === 0) return false;
  if (RESERVED_PRINCIPAL_USERNAMES.has(name)) return true;
  if (name.startsWith("tp")) return true;
  if (name.startsWith("systemd-")) return true;
  return name.endsWith("-grp");
}
