---
turbopanel_install_root: /opt/turbopanel
turbopanel_user: turbopanel
turbopanel_group: turbopanel
turbopanel_vendor_dir: "{{ turbopanel_install_root }}/vendor"
turbopanel_node: "{{ turbopanel_vendor_dir }}/node/current/bin/node"
turbopanel_deno: "{{ turbopanel_vendor_dir }}/deno/current/deno"
turbopanel_runtime_path: "{{ turbopanel_vendor_dir }}/node/current/bin:{{ turbopanel_vendor_dir }}/deno/current:{{ turbopanel_vendor_dir }}/caddy/current:/usr/bin:/bin"
turbopanel_platform_dir: "{{ turbopanel_install_root }}/platform"
turbopanel_daemon_dir: "{{ turbopanel_platform_dir }}/daemon"
turbopanel_daemon_dist_dir: "{{ turbopanel_daemon_dir }}/dist"
force_compile: false
